#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : compat-opencv-soname42
Version  : 4.2.0
Release  : 123
URL      : https://github.com/opencv/opencv/archive/4.2.0/opencv-4.2.0.tar.gz
Source0  : https://github.com/opencv/opencv/archive/4.2.0/opencv-4.2.0.tar.gz
Summary  : Open Source Computer Vision Library
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 HPND IJG JasPer-2.0 LGPL-2.1 Libpng MIT libtiff
Requires: compat-opencv-soname42-lib = %{version}-%{release}
Requires: compat-opencv-soname42-license = %{version}-%{release}
BuildRequires : VTK-dev
BuildRequires : ade-data
BuildRequires : ade-dev
BuildRequires : apache-ant
BuildRequires : beautifulsoup4
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : ccache
BuildRequires : cmake
BuildRequires : doxygen
BuildRequires : eigen-data
BuildRequires : eigen-dev
BuildRequires : gdal-dev
BuildRequires : glib-dev
BuildRequires : glibc-dev
BuildRequires : gstreamer-dev
BuildRequires : gtk3-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : libgphoto2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : librealsense-dev
BuildRequires : libva-dev
BuildRequires : libva-intel-driver
BuildRequires : libwebp-dev
BuildRequires : mesa-dev
BuildRequires : numpy
BuildRequires : ocl-icd-dev
BuildRequires : openblas
BuildRequires : opencl-headers-dev
BuildRequires : opencv-dev
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : openjdk11-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libswscale)
BuildRequires : protobuf-dev
BuildRequires : pugixml-dev
BuildRequires : python3-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : tbb-dev
BuildRequires : v4l-utils-dev
BuildRequires : zlib-dev

%description
A demo of the Java wrapper for OpenCV with two examples:
1) feature detection and matching and
2) face detection.
The examples are coded in Scala and Java.
Anyone familiar with Java should be able to read the Scala examples.
Please feel free to contribute code examples in Scala or Java, or any JVM language.

%package lib
Summary: lib components for the compat-opencv-soname42 package.
Group: Libraries
Requires: compat-opencv-soname42-license = %{version}-%{release}

%description lib
lib components for the compat-opencv-soname42 package.


%package license
Summary: license components for the compat-opencv-soname42 package.
Group: Default

%description license
license components for the compat-opencv-soname42 package.


%prep
%setup -q -n opencv-4.2.0
cd %{_builddir}/opencv-4.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1595454040
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%cmake .. -DCMAKE_INSTALL_LIBDIR:PATH=lib64 \
-DWITH_FFMPEG=Off \
-DWITH_1394=OFF \
-DWITH_GSTREAMER=ON \
-DWITH_IPP=OFF \
-DWITH_JASPER=OFF \
-DWITH_WEBP=ON \
-DWITH_OPENEXR=OFF \
-DWITH_TIFF=OFF \
-DENABLE_SSE42=ON \
-DWITH_TBB=ON \
-DWITH_OPENMP=ON \
-DWITH_VA=ON \
-DWITH_VULKAN=ON \
-DCMAKE_BUILD_TYPE=ReleaseWithDebInfo \
-DWITH_GSTREAMER=1 \
-DINSTALL_PYTHON_EXAMPLES=1 \
-DCPU_DISPATCH=AVX,AVX2,AVX512_SKX \
-DLIB_SUFFIX= \
-DBUILD_EXAMPLES=ON \
-DBUILD_TESTS=ON \
-DBUILD_PERF_TESTS=ON \
-DINSTALL_TESTS=ON \
-DINSTALL_C_EXAMPLES=ON \
-DINSTALL_PYTHON_EXAMPLES=ON \
-DBUILD_JAVA=ON \
-DOPENCV_PYTHON_INSTALL_PATH=/usr/lib/python3.8/site-packages/ \
-DOPENCV_GENERATE_PKGCONFIG=ON \
-DOPENCV_CONFIG_INSTALL_PATH=lib64/cmake/opencv4
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1595454040
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-opencv-soname42
cp %{_builddir}/opencv-4.2.0/3rdparty/cpufeatures/LICENSE %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/ec4468ecfe59c46406d4fc5aca1cee2a83c4d93e
cp %{_builddir}/opencv-4.2.0/3rdparty/ffmpeg/license.txt %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/0aacebb8a54d52a40db8d2d449eceb42f66e198b
cp %{_builddir}/opencv-4.2.0/3rdparty/include/opencl/LICENSE.txt %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/7235f6784b4eae4c40a259dcecc7a20e6c487263
cp %{_builddir}/opencv-4.2.0/3rdparty/ittnotify/src/ittnotify/LICENSE.BSD %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/4f83a9480069279bc79a7af6990b9a546a1d0c02
cp %{_builddir}/opencv-4.2.0/3rdparty/ittnotify/src/ittnotify/LICENSE.GPL %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/49709bd29acf27e87953e37e63bb68373347a805
cp %{_builddir}/opencv-4.2.0/3rdparty/libjasper/LICENSE %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/14b5d0210560128e1a5d5204698cf705011ef792
cp %{_builddir}/opencv-4.2.0/3rdparty/libjasper/copyright %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/a6c8c1690157753de298c1ea2a66a2400d1ab5a3
cp %{_builddir}/opencv-4.2.0/3rdparty/libjpeg-turbo/LICENSE.md %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/a5f4d6f407de11b9ce0fef27e335ddcaeded9f2d
cp %{_builddir}/opencv-4.2.0/3rdparty/libpng/LICENSE %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/fc3951ba26fe1914759f605696a1d23e3b41766f
cp %{_builddir}/opencv-4.2.0/3rdparty/libtiff/COPYRIGHT %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/a2f64f2a85f5fd34bda8eb713c3aad008adbb589
cp %{_builddir}/opencv-4.2.0/3rdparty/libwebp/COPYING %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/59cd938fcbd6735b1ef91781280d6eb6c4b7c5d9
cp %{_builddir}/opencv-4.2.0/3rdparty/openexr/LICENSE %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/72f59fbac43fa1a7f0607d7fdba747832e626656
cp %{_builddir}/opencv-4.2.0/3rdparty/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/a0bcc878d7e7181b120ae51837c8d1703fe919ab
cp %{_builddir}/opencv-4.2.0/3rdparty/quirc/LICENSE %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/eaa22397809541edc6c7678716c4929f4977ee32
cp %{_builddir}/opencv-4.2.0/LICENSE %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/4b0044393617ff5e7e074c7a8db7751e4c12cdfc
cp %{_builddir}/opencv-4.2.0/modules/core/3rdparty/SoftFloat/COPYING.txt %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/91a334a8403de4f677844cfcf4067720be0bb802
cp %{_builddir}/opencv-4.2.0/modules/dnn/src/torch/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/compat-opencv-soname42/99d45ca0d503d7988a486e0d4f95058f89e14115
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}/usr/bin/opencv_perf_calib3d
rm -f %{buildroot}/usr/bin/opencv_perf_core
rm -f %{buildroot}/usr/bin/opencv_perf_dnn
rm -f %{buildroot}/usr/bin/opencv_perf_features2d
rm -f %{buildroot}/usr/bin/opencv_perf_imgcodecs
rm -f %{buildroot}/usr/bin/opencv_perf_imgproc
rm -f %{buildroot}/usr/bin/opencv_perf_objdetect
rm -f %{buildroot}/usr/bin/opencv_perf_photo
rm -f %{buildroot}/usr/bin/opencv_perf_stitching
rm -f %{buildroot}/usr/bin/opencv_perf_video
rm -f %{buildroot}/usr/bin/opencv_perf_videoio
rm -f %{buildroot}/usr/bin/opencv_test_calib3d
rm -f %{buildroot}/usr/bin/opencv_test_core
rm -f %{buildroot}/usr/bin/opencv_test_dnn
rm -f %{buildroot}/usr/bin/opencv_test_features2d
rm -f %{buildroot}/usr/bin/opencv_test_flann
rm -f %{buildroot}/usr/bin/opencv_test_highgui
rm -f %{buildroot}/usr/bin/opencv_test_imgcodecs
rm -f %{buildroot}/usr/bin/opencv_test_imgproc
rm -f %{buildroot}/usr/bin/opencv_test_ml
rm -f %{buildroot}/usr/bin/opencv_test_objdetect
rm -f %{buildroot}/usr/bin/opencv_test_photo
rm -f %{buildroot}/usr/bin/opencv_test_stitching
rm -f %{buildroot}/usr/bin/opencv_test_video
rm -f %{buildroot}/usr/bin/opencv_test_videoio
rm -f %{buildroot}/usr/bin/opencv_annotation
rm -f %{buildroot}/usr/bin/opencv_interactive-calibration
rm -f %{buildroot}/usr/bin/opencv_version
rm -f %{buildroot}/usr/bin/opencv_visualisation
rm -f %{buildroot}/usr/bin/setup_vars_opencv4.sh
rm -f %{buildroot}/usr/include/opencv4/opencv2/calib3d.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/calib3d/calib3d.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/calib3d/calib3d_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/core.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/affine.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/async.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/base.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/bindings_utils.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/bufferpool.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/check.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/core.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/core_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda.inl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/block.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/border_interpolate.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/color.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/common.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/datamov_utils.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/detail/color_detail.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/detail/reduce.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/detail/reduce_key_val.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/detail/transform_detail.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/detail/type_traits_detail.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/detail/vec_distance_detail.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/dynamic_smem.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/emulation.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/filters.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/funcattrib.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/functional.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/limits.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/reduce.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/saturate_cast.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/scan.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/simd_functions.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/transform.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/type_traits.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/utility.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/vec_distance.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/vec_math.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/vec_traits.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/warp.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/warp_reduce.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda/warp_shuffle.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda_stream_accessor.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cuda_types.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cv_cpu_dispatch.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cv_cpu_helper.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cvdef.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cvstd.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cvstd.inl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/cvstd_wrapper.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/detail/async_promise.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/detail/exception_ptr.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/directx.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/eigen.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/fast_math.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/hal.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/interface.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin_avx.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin_avx512.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin_cpp.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin_forward.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin_msa.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin_neon.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin_sse.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin_sse_em.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin_vsx.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/intrin_wasm.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/msa_macros.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/hal/simd_utils.impl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/mat.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/mat.inl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/matx.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/neon_utils.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/ocl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/ocl_genbase.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/ocl_defs.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/opencl_info.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/opencl_svm.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_clamdblas.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_clamdfft.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_core_wrappers.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_gl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/autogenerated/opencl_gl_wrappers.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_clamdblas.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_clamdfft.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_core.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_gl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_gl_wrappers.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_20.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_definitions.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opencl/runtime/opencl_svm_hsa_extension.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/opengl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/operations.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/optim.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/ovx.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/persistence.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/saturate.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/simd_intrinsics.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/softfloat.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/sse_utils.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/traits.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/types.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/types_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/utility.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/utils/allocator_stats.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/utils/allocator_stats.impl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/utils/filesystem.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/utils/instrumentation.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/utils/logger.defines.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/utils/logger.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/utils/logtag.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/utils/tls.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/utils/trace.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/va_intel.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/version.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/core/vsx_utils.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/cvconfig.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/dnn.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/dnn/all_layers.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/dnn/dict.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/dnn/dnn.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/dnn/dnn.inl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/dnn/layer.details.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/dnn/layer.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/dnn/shape_utils.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/dnn/utils/inference_engine.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/dnn/version.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/features2d.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/features2d/features2d.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/features2d/hal/interface.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/all_indices.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/allocator.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/any.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/autotuned_index.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/composite_index.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/config.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/defines.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/dist.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/dummy.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/dynamic_bitset.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/flann.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/flann_base.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/general.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/ground_truth.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/hdf5.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/heap.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/hierarchical_clustering_index.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/index_testing.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/kdtree_index.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/kdtree_single_index.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/kmeans_index.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/linear_index.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/logger.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/lsh_index.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/lsh_table.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/matrix.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/miniflann.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/nn_index.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/object_factory.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/params.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/random.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/result_set.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/sampling.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/saving.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/simplex_downhill.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/flann/timer.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/highgui.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/highgui/highgui.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/highgui/highgui_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgcodecs.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgcodecs/imgcodecs.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgcodecs/imgcodecs_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgcodecs/ios.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgcodecs/legacy/constants_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgproc.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgproc/detail/gcgraph.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgproc/hal/hal.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgproc/hal/interface.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgproc/imgproc.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgproc/imgproc_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/imgproc/types_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/ml.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/ml/ml.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/ml/ml.inl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/objdetect.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/objdetect/detection_based_tracker.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/objdetect/objdetect.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/opencv.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/opencv_modules.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/photo.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/photo/cuda.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/photo/legacy/constants_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/photo/photo.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/autocalib.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/blenders.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/camera.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/exposure_compensate.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/matchers.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/motion_estimators.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/seam_finders.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/timelapsers.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/util.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/util_inl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/warpers.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/detail/warpers_inl.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/stitching/warpers.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/video.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/video/background_segm.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/video/legacy/constants_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/video/tracking.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/video/video.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/videoio.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/videoio/cap_ios.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/videoio/legacy/constants_c.h
rm -f %{buildroot}/usr/include/opencv4/opencv2/videoio/registry.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/videoio/videoio.hpp
rm -f %{buildroot}/usr/include/opencv4/opencv2/videoio/videoio_c.h
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/__init__.py
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/__pycache__/__init__.cpython-38.pyc
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/__pycache__/config-3.8.cpython-38.pyc
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/__pycache__/config.cpython-38.pyc
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/__pycache__/load_config_py2.cpython-38.pyc
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/__pycache__/load_config_py3.cpython-38.pyc
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/config-3.8.py
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/config.py
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/load_config_py2.py
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/load_config_py3.py
rm -f %{buildroot}/usr/lib/python3.8/site-packages/cv2/python-3.8/cv2.cpython-38-x86_64-linux-gnu.so
rm -f %{buildroot}/usr/lib64/cmake/opencv4/OpenCVConfig-version.cmake
rm -f %{buildroot}/usr/lib64/cmake/opencv4/OpenCVConfig.cmake
rm -f %{buildroot}/usr/lib64/cmake/opencv4/OpenCVModules-releasewithdebinfo.cmake
rm -f %{buildroot}/usr/lib64/cmake/opencv4/OpenCVModules.cmake
rm -f %{buildroot}/usr/lib64/libopencv_calib3d.so
rm -f %{buildroot}/usr/lib64/libopencv_core.so
rm -f %{buildroot}/usr/lib64/libopencv_dnn.so
rm -f %{buildroot}/usr/lib64/libopencv_features2d.so
rm -f %{buildroot}/usr/lib64/libopencv_flann.so
rm -f %{buildroot}/usr/lib64/libopencv_highgui.so
rm -f %{buildroot}/usr/lib64/libopencv_imgcodecs.so
rm -f %{buildroot}/usr/lib64/libopencv_imgproc.so
rm -f %{buildroot}/usr/lib64/libopencv_ml.so
rm -f %{buildroot}/usr/lib64/libopencv_objdetect.so
rm -f %{buildroot}/usr/lib64/libopencv_photo.so
rm -f %{buildroot}/usr/lib64/libopencv_stitching.so
rm -f %{buildroot}/usr/lib64/libopencv_video.so
rm -f %{buildroot}/usr/lib64/libopencv_videoio.so
rm -f %{buildroot}/usr/lib64/pkgconfig/opencv4.pc
rm -f %{buildroot}/usr/share/licenses/opencv4/SoftFloat-COPYING.txt
rm -f %{buildroot}/usr/share/licenses/opencv4/ittnotify-LICENSE.BSD
rm -f %{buildroot}/usr/share/licenses/opencv4/ittnotify-LICENSE.GPL
rm -f %{buildroot}/usr/share/licenses/opencv4/opencl-headers-LICENSE.txt
rm -f %{buildroot}/usr/share/licenses/opencv4/protobuf-LICENSE
rm -f %{buildroot}/usr/share/licenses/opencv4/protobuf-README.md
rm -f %{buildroot}/usr/share/licenses/opencv4/quirc-LICENSE
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_eye.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_eye_tree_eyeglasses.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_frontalcatface.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_frontalcatface_extended.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_frontalface_alt.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_frontalface_alt2.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_frontalface_alt_tree.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_frontalface_default.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_fullbody.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_lefteye_2splits.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_licence_plate_rus_16stages.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_lowerbody.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_profileface.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_righteye_2splits.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_russian_plate_number.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_smile.xml
rm -f %{buildroot}/usr/share/opencv4/haarcascades/haarcascade_upperbody.xml
rm -f %{buildroot}/usr/share/opencv4/lbpcascades/lbpcascade_frontalcatface.xml
rm -f %{buildroot}/usr/share/opencv4/lbpcascades/lbpcascade_frontalface.xml
rm -f %{buildroot}/usr/share/opencv4/lbpcascades/lbpcascade_frontalface_improved.xml
rm -f %{buildroot}/usr/share/opencv4/lbpcascades/lbpcascade_profileface.xml
rm -f %{buildroot}/usr/share/opencv4/lbpcascades/lbpcascade_silverware.xml
rm -f %{buildroot}/usr/share/opencv4/samples/CMakeLists.txt
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/3calibration.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/CMakeLists.txt
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/application_trace.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/bgfg_segm.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/calibration.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/camshiftdemo.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/cloning_demo.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/cloning_gui.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/connected_components.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/contours2.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/convexhull.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/cout_mat.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/create_mask.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/dbt_face_detection.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/delaunay2.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/demhist.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/detect_blob.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/detect_mser.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/dft.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/digits.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/dis_opticalflow.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/distrans.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/drawing.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/edge.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/ela.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/em.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/facedetect.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/facial_features.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/falsecolor.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/fback.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/ffilldemo.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/filestorage.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/fitellipse.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/grabcut.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/image_alignment.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/imagelist_creator.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/imagelist_reader.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/inpaint.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/intersectExample.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/kalman.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/kmeans.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/laplace.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/letter_recog.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/lkdemo.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/logistic_regression.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/mask_tmpl.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/matchmethod_orb_akaze_brisk.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/minarea.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/morphology2.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/neural_network.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/npr_demo.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/opencv_version.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/pca.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/peopledetect.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/phase_corr.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/points_classifier.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/polar_transforms.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/qrcode.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/segment_objects.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/select3dobj.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/simd_basic.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/smiledetect.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/squares.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/stereo_calib.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/stereo_match.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/stitching.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/stitching_detailed.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/train_HOG.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/train_svmsgd.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/travelsalesman.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/tree_engine.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/videocapture_basic.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/videocapture_camera.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/videocapture_gphoto2_autofocus.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/videocapture_gstreamer_pipeline.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/videocapture_image_sequence.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/videocapture_intelperc.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/videocapture_openni.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/videocapture_starter.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/videowriter_basic.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/warpPerspective_demo.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/cpp/watershed.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/data/Blender_Suzanne1.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/Blender_Suzanne2.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/H1to3p.xml
rm -f %{buildroot}/usr/share/opencv4/samples/data/HappyFish.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/LinuxLogo.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/Megamind.avi
rm -f %{buildroot}/usr/share/opencv4/samples/data/Megamind_bugy.avi
rm -f %{buildroot}/usr/share/opencv4/samples/data/WindowsLogo.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/aero1.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/aero3.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/aloeGT.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/aloeL.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/aloeR.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/apple.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/baboon.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/basketball1.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/basketball2.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/blox.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/board.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/box.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/box_in_scene.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/building.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/butterfly.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/calibration.yml
rm -f %{buildroot}/usr/share/opencv4/samples/data/cards.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/chessboard.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/chicky_512.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/data01.xml
rm -f %{buildroot}/usr/share/opencv4/samples/data/detect_blob.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/digits.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/dnn/action_recongnition_kinetics.txt
rm -f %{buildroot}/usr/share/opencv4/samples/data/dnn/classification_classes_ILSVRC2012.txt
rm -f %{buildroot}/usr/share/opencv4/samples/data/dnn/enet-classes.txt
rm -f %{buildroot}/usr/share/opencv4/samples/data/dnn/object_detection_classes_coco.txt
rm -f %{buildroot}/usr/share/opencv4/samples/data/dnn/object_detection_classes_pascal_voc.txt
rm -f %{buildroot}/usr/share/opencv4/samples/data/dnn/object_detection_classes_yolov3.txt
rm -f %{buildroot}/usr/share/opencv4/samples/data/ela_modified.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/ela_original.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/ellipses.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/fruits.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/gradient.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/graf1.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/graf3.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/home.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/imageTextN.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/imageTextR.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/intrinsics.yml
rm -f %{buildroot}/usr/share/opencv4/samples/data/left.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left01.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left02.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left03.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left04.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left05.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left06.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left07.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left08.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left09.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left11.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left12.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left13.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left14.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/left_intrinsics.yml
rm -f %{buildroot}/usr/share/opencv4/samples/data/lena.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/lena_tmpl.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/letter-recognition.data
rm -f %{buildroot}/usr/share/opencv4/samples/data/licenseplate_motion.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/mask.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/messi5.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/ml.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/notes.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/opencv-logo-white.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/opencv-logo.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/orange.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/pca_test1.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/pic1.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/pic2.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/pic3.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/pic4.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/pic5.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/pic6.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/right.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right01.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right02.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right03.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right04.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right05.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right06.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right07.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right08.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right09.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right11.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right12.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right13.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/right14.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/rubberwhale1.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/rubberwhale2.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/smarties.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/starry_night.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/stereo_calib.xml
rm -f %{buildroot}/usr/share/opencv4/samples/data/stuff.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/sudoku.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/templ.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/text_defocus.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/text_motion.jpg
rm -f %{buildroot}/usr/share/opencv4/samples/data/tmpl.png
rm -f %{buildroot}/usr/share/opencv4/samples/data/tree.avi
rm -f %{buildroot}/usr/share/opencv4/samples/data/vtest.avi
rm -f %{buildroot}/usr/share/opencv4/samples/dnn/CMakeLists.txt
rm -f %{buildroot}/usr/share/opencv4/samples/dnn/classification.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/dnn/colorization.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/dnn/common.hpp
rm -f %{buildroot}/usr/share/opencv4/samples/dnn/custom_layers.hpp
rm -f %{buildroot}/usr/share/opencv4/samples/dnn/object_detection.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/dnn/openpose.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/dnn/segmentation.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/dnn/text_detection.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/CMakeLists.txt
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/alpha_comp.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/bgfg_segm.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/cascadeclassifier.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/farneback_optical_flow.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/generalized_hough.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/hog.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/houghlines.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/morphology.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/multi.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/pyrlk_optical_flow.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/stereo_match.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/stereo_multi.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/super_resolution.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/surf_keypoint_matcher.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/video_reader.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/gpu/video_writer.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/opencl/CMakeLists.txt
rm -f %{buildroot}/usr/share/opencv4/samples/opencl/display.cpp.inc
rm -f %{buildroot}/usr/share/opencv4/samples/opencl/opencl-opencv-interop.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/opencl/va_intel_interop.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/python/_coverage.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/_doc.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/asift.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/browse.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/calibrate.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/camera_calibration_show_extrinsics.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/camshift.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/coherence.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/color_histogram.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/common.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/contours.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/deconvolution.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/demo.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/dft.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/digits.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/digits_adjust.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/digits_video.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/dis_opt_flow.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/distrans.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/edge.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/facedetect.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/feature_homography.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/find_obj.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/fitline.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/floodfill.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/gabor_threads.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/gaussian_mix.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/grabcut.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/hist.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/houghcircles.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/houghlines.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/inpaint.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/kalman.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/kmeans.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/lappyr.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/letter_recog.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/lk_homography.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/lk_track.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/logpolar.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/morphology.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/mosse.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/mouse_and_match.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/mser.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/opencv_version.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/opt_flow.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/peopledetect.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/plane_ar.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/plane_tracker.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/squares.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/stereo_match.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/stitching.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/stitching_detailed.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/texture_flow.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/tst_scene_render.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/turing.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/video.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/video_threaded.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/video_v4l2.py
rm -f %{buildroot}/usr/share/opencv4/samples/python/watershed.py
rm -f %{buildroot}/usr/share/opencv4/samples/tapi/CMakeLists.txt
rm -f %{buildroot}/usr/share/opencv4/samples/tapi/bgfg_segm.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/tapi/camshift.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/tapi/clahe.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/tapi/dense_optical_flow.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/tapi/hog.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/tapi/opencl_custom_kernel.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/tapi/pyrlk_optical_flow.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/tapi/squares.cpp
rm -f %{buildroot}/usr/share/opencv4/samples/tapi/ufacedetect.cpp
rm -f %{buildroot}/usr/share/opencv4/valgrind.supp
rm -f %{buildroot}/usr/share/opencv4/valgrind_3rdparty.supp
## install_append content
# A bad idea but this will allow things that use pkgconfig to use opencv4
# Probably remove at some point once software updates build detection for new upstream release
#cp %{buildroot}/usr/lib64/pkgconfig/opencv4.pc %{buildroot}/usr/lib64/pkgconfig/opencv.pc
## install_append end

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopencv_calib3d.so.4.2
/usr/lib64/libopencv_calib3d.so.4.2.0
/usr/lib64/libopencv_core.so.4.2
/usr/lib64/libopencv_core.so.4.2.0
/usr/lib64/libopencv_dnn.so.4.2
/usr/lib64/libopencv_dnn.so.4.2.0
/usr/lib64/libopencv_features2d.so.4.2
/usr/lib64/libopencv_features2d.so.4.2.0
/usr/lib64/libopencv_flann.so.4.2
/usr/lib64/libopencv_flann.so.4.2.0
/usr/lib64/libopencv_highgui.so.4.2
/usr/lib64/libopencv_highgui.so.4.2.0
/usr/lib64/libopencv_imgcodecs.so.4.2
/usr/lib64/libopencv_imgcodecs.so.4.2.0
/usr/lib64/libopencv_imgproc.so.4.2
/usr/lib64/libopencv_imgproc.so.4.2.0
/usr/lib64/libopencv_ml.so.4.2
/usr/lib64/libopencv_ml.so.4.2.0
/usr/lib64/libopencv_objdetect.so.4.2
/usr/lib64/libopencv_objdetect.so.4.2.0
/usr/lib64/libopencv_photo.so.4.2
/usr/lib64/libopencv_photo.so.4.2.0
/usr/lib64/libopencv_stitching.so.4.2
/usr/lib64/libopencv_stitching.so.4.2.0
/usr/lib64/libopencv_video.so.4.2
/usr/lib64/libopencv_video.so.4.2.0
/usr/lib64/libopencv_videoio.so.4.2
/usr/lib64/libopencv_videoio.so.4.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-opencv-soname42/0aacebb8a54d52a40db8d2d449eceb42f66e198b
/usr/share/package-licenses/compat-opencv-soname42/14b5d0210560128e1a5d5204698cf705011ef792
/usr/share/package-licenses/compat-opencv-soname42/49709bd29acf27e87953e37e63bb68373347a805
/usr/share/package-licenses/compat-opencv-soname42/4b0044393617ff5e7e074c7a8db7751e4c12cdfc
/usr/share/package-licenses/compat-opencv-soname42/4f83a9480069279bc79a7af6990b9a546a1d0c02
/usr/share/package-licenses/compat-opencv-soname42/59cd938fcbd6735b1ef91781280d6eb6c4b7c5d9
/usr/share/package-licenses/compat-opencv-soname42/7235f6784b4eae4c40a259dcecc7a20e6c487263
/usr/share/package-licenses/compat-opencv-soname42/72f59fbac43fa1a7f0607d7fdba747832e626656
/usr/share/package-licenses/compat-opencv-soname42/91a334a8403de4f677844cfcf4067720be0bb802
/usr/share/package-licenses/compat-opencv-soname42/99d45ca0d503d7988a486e0d4f95058f89e14115
/usr/share/package-licenses/compat-opencv-soname42/a0bcc878d7e7181b120ae51837c8d1703fe919ab
/usr/share/package-licenses/compat-opencv-soname42/a2f64f2a85f5fd34bda8eb713c3aad008adbb589
/usr/share/package-licenses/compat-opencv-soname42/a5f4d6f407de11b9ce0fef27e335ddcaeded9f2d
/usr/share/package-licenses/compat-opencv-soname42/a6c8c1690157753de298c1ea2a66a2400d1ab5a3
/usr/share/package-licenses/compat-opencv-soname42/eaa22397809541edc6c7678716c4929f4977ee32
/usr/share/package-licenses/compat-opencv-soname42/ec4468ecfe59c46406d4fc5aca1cee2a83c4d93e
/usr/share/package-licenses/compat-opencv-soname42/fc3951ba26fe1914759f605696a1d23e3b41766f
